name: Fail Workflow

on:
  push:
    branches:
      - main

jobs:
  fail_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: wpcom
        path: .
